### ISSUE TITLE
Add Vercel monthly bill to readme. 

### ISSUE THREAD

**Issue by zommerberg** [ethanniser/NextFaster#69]
Could you add a note about the traffic and monthly expenses, so everyone has a clear understanding of the maintenance costs for this web app?

**Comment by Gitstar-OC** [comment]
Yes, this seems like a good idea so that we can think if we would want to implement it or not as speed matters in some cases!

**Comment by ethanniser** [comment]
bc3f0c3
https://github.com/ethanniser/NextFaster#costs
